/**
 * audit.mjs
 *
 * The measurement half of the SEO system: parse a built page exactly as a
 * crawler would see it, and model Vercel's routing so a URL resolves to the
 * same bytes in the audit as it does in production.
 *
 * Kept separate from scripts/seo-audit.mjs so the same primitives back both the
 * CLI report and the regression suite — a test that re-implements its own HTML
 * parser drifts from the tool that produced the numbers in the report.
 *
 * Deliberately dependency-free. The prerendered markup we emit is generated by
 * src/seo/render.js and is therefore predictable; a full HTML parser would buy
 * nothing here and would put a parser dependency in the build path.
 */

import fs from 'node:fs';
import path from 'node:path';

import { SITE_URL } from './site.js';

/** The host a crawler requests unless a caller says otherwise. */
const CANONICAL_HOST = new URL(SITE_URL).host;

/* ------------------------------------------------------------------ *
 * HTML extraction
 * ------------------------------------------------------------------ */

const VOID_CONTENT_TAGS = /<(script|style|noscript|template)\b[^>]*>[\s\S]*?<\/\1>/gi;

/** Decode the handful of entities our own renderer emits. */
export function decodeEntities(value) {
  return String(value)
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&rsaquo;/g, '›')
    .replace(/&middot;/g, '·')
    .replace(/&copy;/g, '©')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&');
}

function attr(tag, name) {
  const match = tag.match(new RegExp(`${name}\\s*=\\s*("([^"]*)"|'([^']*)')`, 'i'));
  if (!match) return undefined;
  return decodeEntities(match[2] ?? match[3] ?? '');
}

function metaContent(html, selector, value) {
  const re = new RegExp(`<meta\\b[^>]*\\b${selector}\\s*=\\s*["']${value}["'][^>]*>`, 'i');
  const match = html.match(re);
  return match ? attr(match[0], 'content') : undefined;
}

function allTags(html, tagName) {
  const re = new RegExp(`<${tagName}\\b[^>]*>([\\s\\S]*?)</${tagName}>`, 'gi');
  const out = [];
  let match;
  while ((match = re.exec(html))) out.push(match[1]);
  return out;
}

/** Visible text: tags stripped, entities decoded, whitespace collapsed. */
export function textOf(html) {
  return decodeEntities(
    String(html).replace(VOID_CONTENT_TAGS, ' ').replace(/<[^>]+>/g, ' ')
  )
    .replace(/\s+/g, ' ')
    .trim();
}

export function wordCount(text) {
  return text ? text.split(/\s+/).filter(Boolean).length : 0;
}

/**
 * Parse one HTML document into the signals an SEO audit cares about.
 *
 * `mainText` excludes the shared nav/breadcrumb/footer chrome so that
 * "unique words" measures the page's own content rather than the template.
 */
export function parseHtml(html) {
  const headMatch = html.match(/<head\b[^>]*>([\s\S]*?)<\/head>/i);
  const head = headMatch ? headMatch[1] : html;
  const bodyMatch = html.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i);
  const body = bodyMatch ? bodyMatch[1] : html;

  const titleMatch = head.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i);
  const canonicalMatch = head.match(/<link\b[^>]*rel\s*=\s*["']canonical["'][^>]*>/i);

  const jsonLd = [];
  const jsonLdErrors = [];
  const ldRe = /<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let ld;
  while ((ld = ldRe.exec(html))) {
    const raw = ld[1].replace(/\\u003c/g, '<').replace(/\\u003e/g, '>').replace(/\\u0026/g, '&');
    try {
      jsonLd.push(JSON.parse(raw));
    } catch (error) {
      jsonLdErrors.push(error.message);
    }
  }

  const links = [];
  const linkRe = /<a\b[^>]*href\s*=\s*("([^"]*)"|'([^']*)')[^>]*>([\s\S]*?)<\/a>/gi;
  let a;
  while ((a = linkRe.exec(body))) {
    const href = decodeEntities(a[2] ?? a[3] ?? '');
    links.push({ href, text: textOf(a[4]) });
  }

  const mainMatch = body.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i);
  const prerendered = /data-seo-prerender="true"/.test(body);
  const rootMatch = body.match(/<div id="root"[^>]*>([\s\S]*?)<\/div>\s*(?:<script|<\/body>|$)/i);

  const bodyText = textOf(body);
  const mainText = mainMatch ? textOf(mainMatch[1]) : bodyText;

  return {
    title: titleMatch ? decodeEntities(titleMatch[1]).trim() : undefined,
    description: metaContent(head, 'name', 'description'),
    robots: metaContent(head, 'name', 'robots'),
    canonical: canonicalMatch ? attr(canonicalMatch[0], 'href') : undefined,
    ogTitle: metaContent(head, 'property', 'og:title'),
    ogDescription: metaContent(head, 'property', 'og:description'),
    ogImage: metaContent(head, 'property', 'og:image'),
    ogUrl: metaContent(head, 'property', 'og:url'),
    twitterCard: metaContent(head, 'name', 'twitter:card'),
    h1s: allTags(body, 'h1').map((h) => textOf(h)),
    h2s: allTags(body, 'h2').map((h) => textOf(h)),
    h3s: allTags(body, 'h3').map((h) => textOf(h)),
    jsonLd,
    jsonLdErrors,
    links,
    prerendered,
    hasRootContent: rootMatch ? textOf(rootMatch[1]).length > 0 : prerendered,
    bodyText,
    mainText,
    bodyWords: wordCount(bodyText),
    mainWords: wordCount(mainText),
  };
}

/* ------------------------------------------------------------------ *
 * Vercel routing model
 * ------------------------------------------------------------------ */

/** Convert a Vercel `source` pattern into a RegExp (case-sensitive, like Vercel). */
function sourceToRegExp(source) {
  const pattern = source
    .replace(/[.+?^${}()|[\]\\]/g, '\\$&')
    .replace(/\/:([A-Za-z0-9_]+)\*/g, '(?:/(?<$1>.*))?')
    .replace(/:([A-Za-z0-9_]+)/g, '(?<$1>[^/]+)');
  return new RegExp(`^${pattern}$`);
}

/**
 * Substitute a matched source's captures into a destination template.
 *
 * Vercel interpolates `:path*` and `:name` in the destination; a model that
 * returned the template verbatim would report the redirect target as
 * "https://electricscouts.com/:path*" and could not tell a correct redirect
 * from one pointing at the wrong page.
 */
function fillParams(destination, groups) {
  if (!groups) return destination;
  let out = destination;
  for (const [name, value] of Object.entries(groups)) {
    // The starred form first: ":path*" contains ":path".
    out = out.split(`:${name}*`).join(value ?? '').split(`:${name}`).join(value ?? '');
  }
  return out;
}

/**
 * Resolve a path the way the deployment does: redirects first, then the
 * filesystem, then rewrites, then the 404 page.
 *
 * Modelling this matters because a rewrite that shadows a prerendered file (or
 * a prerendered file that never gets served because a rewrite wins) is exactly
 * the class of bug that makes a page look fine locally and blank to Googlebot.
 */
export function createResolver({ distDir, vercelConfig, host = CANONICAL_HOST }) {
  /**
   * Whether a rule applies to the host being resolved.
   *
   * A Vercel rule can carry `has` conditions, and one of them is the request
   * host. The site uses that to send its .vercel.app aliases — which serve a
   * second, indexable copy of every page — to the canonical origin. Those rules
   * use `source: "/:path*"`, so a model that reads `source` and ignores `has`
   * concludes that every URL on the canonical host is a redirect, and every
   * check built on it becomes nonsense.
   *
   * Only host conditions are modelled. A rule gated on anything else (a cookie,
   * a query parameter, a header) is treated as not applying to a plain crawler
   * request, which is what it is.
   */
  function appliesToHost(rule) {
    const conditions = [...(rule.has || []), ...(rule.missing || [])];
    if (!conditions.length) return true;
    return (rule.has || []).every((c) => c.type === 'host' && c.value === host)
      && (rule.missing || []).every((c) => c.type === 'host' && c.value !== host);
  }

  const redirects = (vercelConfig.redirects || []).filter(appliesToHost).map((r) => ({
    ...r,
    re: sourceToRegExp(r.source),
  }));
  const rewrites = (vercelConfig.rewrites || []).filter(appliesToHost).map((r) => ({
    ...r,
    re: sourceToRegExp(r.source),
  }));

  function readFileFor(pathname) {
    const rel = pathname.replace(/^\/+/, '');
    const candidates = rel
      ? [path.join(distDir, rel, 'index.html'), path.join(distDir, rel)]
      : [path.join(distDir, 'index.html')];
    for (const candidate of candidates) {
      if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
        return { file: candidate, html: fs.readFileSync(candidate, 'utf8') };
      }
    }
    return null;
  }

  return function resolve(rawPath) {
    const pathname = String(rawPath).split('#')[0].split('?')[0] || '/';

    for (const redirect of redirects) {
      const match = pathname.match(redirect.re);
      if (match) {
        return {
          path: pathname,
          status: redirect.permanent === false ? 302 : 301,
          location: fillParams(redirect.destination, match.groups),
          kind: 'redirect',
        };
      }
    }

    const direct = readFileFor(pathname);
    if (direct) {
      return { path: pathname, status: 200, kind: 'static', ...direct };
    }

    for (const rewrite of rewrites) {
      const match = pathname.match(rewrite.re);
      if (!match) continue;
      // API destinations are serverless functions, not files on disk.
      if (rewrite.destination.startsWith('/api/')) {
        return { path: pathname, status: 200, kind: 'function', destination: rewrite.destination };
      }
      const target = readFileFor(rewrite.destination);
      if (target) {
        return {
          path: pathname,
          status: 200,
          kind: 'rewrite',
          destination: rewrite.destination,
          ...target,
        };
      }
    }

    const notFound = readFileFor('/404.html');
    return {
      path: pathname,
      status: 404,
      kind: 'notfound',
      ...(notFound || {}),
    };
  };
}

/* ------------------------------------------------------------------ *
 * Similarity
 * ------------------------------------------------------------------ */

/** Word shingles, used to measure how much of one page also appears in another. */
export function shingles(text, size = 5) {
  const words = String(text).toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter(Boolean);
  const set = new Set();
  for (let i = 0; i + size <= words.length; i += 1) {
    set.add(words.slice(i, i + size).join(' '));
  }
  return set;
}

export function jaccard(a, b) {
  if (!a.size && !b.size) return 1;
  let intersection = 0;
  for (const item of a) if (b.has(item)) intersection += 1;
  return intersection / (a.size + b.size - intersection);
}

/**
 * Mean pairwise similarity within a group, sampled when the group is large.
 * 144 city pages would otherwise mean ~10k comparisons per run.
 */
export function meanSimilarity(texts, { sample = 40, size = 5 } = {}) {
  const picked = texts.length > sample
    ? texts.filter((_, i) => i % Math.ceil(texts.length / sample) === 0).slice(0, sample)
    : texts;
  const sets = picked.map((text) => shingles(text, size));
  if (sets.length < 2) return 0;
  let total = 0;
  let pairs = 0;
  for (let i = 0; i < sets.length; i += 1) {
    for (let j = i + 1; j < sets.length; j += 1) {
      total += jaccard(sets[i], sets[j]);
      pairs += 1;
    }
  }
  return pairs ? total / pairs : 0;
}

/**
 * Similarity thresholds, in 7-word shingles over <main> text.
 *
 * Exported so scripts/seo-audit.mjs and scripts/seo-url-audit.mjs cannot drift
 * apart, which they had: one gated a family mean at 0.55, the other gated pairs
 * at 0.60, and neither number was reachable. The highest family mean this site
 * can produce is 0.221 and its worst pair is 0.458, so both audits reported
 * clean because their gates sat above anything the site could generate rather
 * than because the pages were distinct.
 *
 * Set from the measured distribution instead: worst pair 0.458 (Gaithersburg
 * and Rockville, two Maryland cities sharing a utility, a supplier list and a
 * rate table), highest p95 0.374 (utilities). Close enough to bite when a new
 * page lands on top of an existing one, with enough headroom that today's
 * pages pass.
 */
export const SIMILARITY_PAIR_WARN = 0.50;
export const SIMILARITY_PAIR_FAIL = 0.65;
export const SIMILARITY_P95_WARN = 0.45;

/**
 * Pairwise similarity across a family: mean, p95, max, and the worst pair.
 *
 * meanSimilarity answers a different question and cannot answer this one. It
 * averages every pair and samples 40 texts, so duplication that is concentrated
 * rather than spread is invisible to it twice over. The city family is the
 * case: 144 pages whose mean is 0.14, containing a Gaithersburg/Rockville pair
 * at 0.46 because two neighbouring Maryland cities share a utility, a supplier
 * list and a rate table. An average cannot see one hot pair in ten thousand,
 * and sampling every fourth page can drop the pair from the comparison set
 * entirely. Google drops the page, not the average.
 *
 * So this reports the tail: no sampling, every pair, and the worst one named so
 * a finding says which two pages to look at.
 */
export function similarityProfile(entries, { size = 7 } = {}) {
  const sets = entries.map((entry) => ({ id: entry.id, set: shingles(entry.text, size) }));
  const scores = [];
  let worst = { score: 0, a: null, b: null };

  for (let i = 0; i < sets.length; i += 1) {
    for (let j = i + 1; j < sets.length; j += 1) {
      const score = jaccard(sets[i].set, sets[j].set);
      scores.push(score);
      if (score > worst.score) worst = { score, a: sets[i].id, b: sets[j].id };
    }
  }

  if (!scores.length) return { pairs: 0, mean: 0, p95: 0, max: 0, worst };
  scores.sort((a, b) => a - b);
  return {
    pairs: scores.length,
    mean: scores.reduce((sum, value) => sum + value, 0) / scores.length,
    p95: scores[Math.floor((scores.length - 1) * 0.95)],
    max: scores[scores.length - 1],
    worst,
  };
}

/** Group values by a key, returning only the groups with more than one member. */
export function duplicateGroups(entries, keyFn) {
  const groups = new Map();
  for (const entry of entries) {
    const key = keyFn(entry);
    if (!key) continue;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(entry);
  }
  return [...groups.entries()].filter(([, members]) => members.length > 1);
}
